<?php
/**
 * @file
 * Magento 2 module - Sequence by environment
 * Copyright (C) 2022  Bluebirdday
 *
 * This program is free software: you can redistribute it and/or modify it under the terms
 * of the GNU General Public License as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Category view template
 *
 * @var $block \Bluebirdday\Subcategories\Block\Subcategories
 * @var $escaper \Magento\Framework\Escaper
 */
$collection = $block->getCategoryCollection();
$helper = $block->helper();
?>
<?php if ($collection->getSize()): ?>
    <h3 class="subcategory-list__title"><span><?php /* @escapeNotVerified */ echo __('Categories') ?></span></h3>
    <div class="row subcategory__wrapper">
        <?php foreach ($collection as $category): ?>
            <?php
            /** @var \Magento\Catalog\Model\Category $category */
            $uspList = $helper->getListUsp($category);
            $noThumbnailClass = $helper->getThumbnail($category) ? '' : ' subcategory-item__image-wrapper--placeholder';
            $thumbnailUrl = $helper->getThumbnailUrl($category);
            $subcategoryUrl = $subcategoryUrl = $category->getUrl(); ?>
            <?php if ($thumbnailUrl && $subcategoryUrl): ?>
                <div class="subcategory-column">
                    <div class="subcategory-item">
                        <a class="subcategory-item__link" href="<?= $escaper->escapeHtml($subcategoryUrl); ?>">
                            <div class="subcategory-item__image-wrapper<?= $noThumbnailClass ?>" data-match-height="subcategory-item-image-wrapper">
                                <img class="subcategory-item__image" src="<?= $escaper->escapeHtml($thumbnailUrl); ?>" />
                            </div>
                        </a>

                        <a href="<?= $escaper->escapeHtml($subcategoryUrl); ?>" class="subcategory-item__text-link">
                            <span class="subcategory-item__name"><?= $escaper->escapeHtml($category->getName())?></span>
                        </a>

                        <?php if ($uspList): ?>
                            <div class="subcategory-item__usp">
                                <?= $uspList; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
